{"misc/proper_plugin.py": [{".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "is_special_target", "line": 55, "column": 25, "severity": "error", "message": "Expression type contains \"Any\" (has type \"Type[CallableType]\")", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 55, 55], "target": "proper_plugin.is_special_target"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "is_special_target", "line": 55, "column": 25, "severity": "error", "message": "Expression type contains \"Any\" (has type \"Type[CallableType]\")", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 55, 55], "target": "proper_plugin.is_special_target"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "is_dangerous_target", "line": 101, "column": 23, "severity": "error", "message": "Expression type contains \"Any\" (has type \"Type[CallableType]\")", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 101, 101], "target": "proper_plugin.is_dangerous_target"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "is_dangerous_target", "line": 101, "column": 23, "severity": "error", "message": "Expression type contains \"Any\" (has type \"Type[CallableType]\")", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 101, 101], "target": "proper_plugin.is_dangerous_target"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "get_proper_type_instance", "line": 135, "column": 23, "severity": "error", "message": "Expression has type \"Any\"", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 135, 135], "target": "proper_plugin.get_proper_type_instance"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "get_proper_type_instance", "line": 135, "column": 23, "severity": "error", "message": "Expression has type \"Any\"", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 135, 135], "target": "proper_plugin.get_proper_type_instance"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "get_proper_type_instance", "line": 135, "column": 23, "severity": "error", "message": "Expression has type \"Any\"", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 135, 135], "target": "proper_plugin.get_proper_type_instance"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "get_proper_type_instance", "line": 136, "column": 22, "severity": "error", "message": "Expression has type \"Any\"", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 136, 136], "target": "proper_plugin.get_proper_type_instance"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "get_proper_type_instance", "line": 136, "column": 22, "severity": "error", "message": "Expression has type \"Any\"", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 136, 136], "target": "proper_plugin.get_proper_type_instance"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": "get_proper_type_instance", "line": 137, "column": 20, "severity": "error", "message": "Expression has type \"Any\"", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "misc", "description": "Miscellaneous other checks", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 137, 137], "target": "proper_plugin.get_proper_type_instance"}, {".class": "mypy.errors.ErrorInfo", "import_ctx": [], "file": "misc/proper_plugin.py", "module": "proper_plugin", "type": null, "function_or_member": null, "line": 134, "column": -1, "severity": "error", "message": "No error code on \"type: ignore\" comment", "code": {".class": "mypy.errorcodes.ErrorCode", "code": "no-error-code", "description": "No error code specified in ignore comment", "category": "General", "default_enabled": true}, "blocker": false, "only_once": false, "allow_dups": false, "origin": ["misc/proper_plugin.py", 134, 134], "target": null}]}